name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Login ACR
      run: echo ${{ secrets.ACR_PASSWORD }} | docker login carlos69lamejor.azurecr.io -u ${{ secrets.ACR_USERNAME }} --password-stdin

    - name: Build App1
      run: docker build -t carlos69lamejor.azurecr.io/app1:v1 ./app1

    - name: Push App1
      run: docker push carlos69lamejor.azurecr.io/app1:v1

    - name: Build App2
      run: docker build -t carlos69lamejor.azurecr.io/app2:v1 ./app2

    - name: Push App2
      run: docker push carlos69lamejor.azurecr.io/app2:v1

    - name: Get AKS credentials
      run: az aks get-credentials --resource-group rg-k8s-lab --name aks-lab --admin

    - name: Deploy to AKS
      run: kubectl apply -f k8s/